name: memory_plugin
description: memory plugin.
version: 0.0.2
homepage: https://github.com/FakenMaster/memory_plugin.git

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.faken.memory.memory_plugin
        pluginClass: MemoryPlugin
      ios:
        pluginClass: MemoryPlugin
      windows:
        pluginClass: MemoryPlugin
      macos:
        pluginClass: MemoryPlugin
      linux:
        pluginClass: MemoryPlugin
      web:
        pluginClass: MemoryPluginWeb
        fileName: memory_plugin_web.dart
